name: mywishstash
description: "MyWishStash: cria e partilha listas de desejos, adiciona produtos com imagens (Cloudinary), acompanha quedas de preço, recebe notificações (FCM) e sincroniza tudo em tempo real via Firebase."
publish_to: 'none'
version: 0.1.4+5

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path_provider: ^2.1.5
  share_plus: ^11.1.0
  file_picker: ^8.0.0
  google_sign_in: ^7.1.1
  intl_phone_field: ^3.1.1
  flutter_contacts: ^1.1.9+2
  image_picker: ^1.0.4
  http: ^1.2.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  intl: ^0.20.2
  
  # Firebase (Authentication + Database + Cloud Messaging + Cloud Functions)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_messaging: ^16.0.0
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  flutter_local_notifications: ^19.4.1
  firebase_analytics: ^12.0.0
  
  # Cloudinary (Images)
  cloudinary_public: ^0.23.1
  
  flutter_sharing_intent: ^1.1.1
  html: ^0.15.6
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
