name: wishlist_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  share_plus: ^10.0.0
  google_sign_in: ^6.2.1
  intl_phone_field: ^3.1.1
  #receive_sharing_intent: ^1.4.5
  permission_handler: ^12.0.1
  flutter_contacts: ^1.1.9+2
  image_picker: ^1.0.4
  http: ^1.2.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  supabase_flutter: ^2.9.1
  sms_autofill: ^2.3.0
  image: ^4.0.17
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true