name: wishlist_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path_provider: ^2.1.5
  share_plus: ^11.1.0
  google_sign_in: 6.1.6
  intl_phone_field: ^3.1.1
  flutter_contacts: ^1.1.9+2
  image_picker: ^1.0.4
  http: ^1.2.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  intl: ^0.20.2
  
  # Firebase (Authentication + Database + Cloud Messaging + Cloud Functions)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  cloud_firestore: ^4.13.6
  cloud_functions: ^4.6.0
  flutter_local_notifications: ^17.0.0
  
  # Cloudinary (Images)
  cloudinary_public: ^0.21.0
  
  flutter_sharing_intent: ^1.1.1
  html: ^0.15.6
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  web: false
  windows: false
  macos: false
  linux: false
  image_path: "assets/images/app_icon.jpg"
  adaptive_icon_background: "#FF6B9D"
  adaptive_icon_foreground: "assets/images/app_icon.jpg"

flutter_native_splash:
  color: "#FF6B9D"
  image: assets/images/app_icon.jpg
  android: true
  ios: false
  web: false
  windows: false
  macos: false
  linux: false
  android_12:
    image: assets/images/app_icon.jpg
    color: "#FF6B9D"